# Dependabot Configuration
#
# References:
#
# - https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

---
version: 2
registries:
  github:
    token: ${{ secrets.PAT_BOT }}
    type: npm-registry
    url: https://npm.pkg.github.com
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: ci
      include: scope
    directory: /
    labels:
      - scope:dependencies
      - type:ci
    reviewers:
      - flex-development/dependabot-review
      - flexdevelopment
    schedule:
      interval: daily
  - package-ecosystem: npm
    commit-message:
      prefix: build
      include: scope
    directory: /
    ignore:
      - dependency-name: vitepress
    labels:
      - scope:dependencies
      - type:build
    registries:
      - github
    reviewers:
      - flex-development/dependabot-review
      - flexdevelopment
    schedule:
      interval: daily
