# Dependabot Configuration
#
# References:
#
# - https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    labels:
      - scope:dependencies
      - type:ci
    reviewers:
      - flex-development/dependabot-review
      - flexdevelopment
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: build
      include: scope
    ignore:
      - dependency-name: '@types/node'
    labels:
      - scope:dependencies
      - type:build
    reviewers:
      - flex-development/dependabot-review
      - flexdevelopment
