# Dependabot Configuration
#
# References:
#
# - https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

---
version: 2
registries:
  github:
    token: ${{ secrets.PAT_BOT }}
    type: npm-registry
    url: https://npm.pkg.github.com
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: ci
      include: scope
    directory: /
    labels:
      - scope:dependencies
      - type:ci
    reviewers:
      - flex-development/dependabot-review
      - flexdevelopment
    schedule:
      interval: daily
  - package-ecosystem: npm
    commit-message:
      prefix: build
      include: scope
    directory: /
    groups:
      conventional-changelog:
        patterns:
          - '@types/conventional-changelog'
          - '@types/conventional-changelog-core'
          - '@types/conventional-changelog-writer'
          - '@types/conventional-recommended-bump'
          - '@types/git-raw-commits'
          - conventional-changelog
          - conventional-changelog-conventionalcommits
          - conventional-changelog-core
          - conventional-changelog-writer
          - conventional-recommended-bump
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      vitest:
        patterns:
          - '@vitest/*'
          - vitest
    labels:
      - scope:dependencies
      - type:build
    registries:
      - github
    reviewers:
      - flex-development/dependabot-review
      - flexdevelopment
    schedule:
      interval: daily
