# Dependabot Configuration
#
# References:
#
# - https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

---
version: 2
registries:
  github:
    token: ${{ secrets.GH_REGISTRY_TOKEN }}
    type: npm-registry
    url: https://npm.pkg.github.com
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: ci
      include: scope
    directory: /
    labels:
      - scope:dependencies
      - type:ci
    schedule:
      interval: daily
  - package-ecosystem: npm
    commit-message:
      prefix: build
      include: scope
    directory: /
    groups:
      commitlint:
        patterns:
          - '@commitlint/*'
      eslint:
        patterns:
          - '@types/eslint'
          - eslint
      flex-development:
        patterns:
          - '@flex-development/*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      vitest:
        patterns:
          - '@vitest/*'
          - vitest*
    ignore:
      - dependency-name: eslint-plugin-import
      - dependency-name: vue-tsc
    labels:
      - scope:dependencies
      - type:build
    registries:
      - github
    schedule:
      interval: daily
