# https://yarnpkg.com/configuration/yarnrc

changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - '!{docs,src/**,{CHANGELOG,LICENSE,README}.md,package.json}'
  - '**/*.snap'
  - '**/*.spec.mts'
  - '**/*.spec-d.mts'

compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

enableInlineBuilds: true

enableTransparentWorkspaces: false

injectEnvironmentFiles:
  - .env.repo?
  - .env.vars?

nmHoistingLimits: dependencies

nodeLinker: node-modules

npmScopes:
  flex-development:
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN:-$GH_REGISTRY_TOKEN}
    npmRegistryServer: https://npm.pkg.github.com

patchFolder: ./patches

yarnPath: .yarn/releases/yarn-4.5.1.cjs
