# https://yarnpkg.com/configuration/yarnrc

changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - '!{docs,src/**,{CHANGELOG,LICENSE,README}.md,package.json}'
  - '**/*.snap'
  - '**/*.spec.ts'
  - '**/*.spec-d.ts'

defaultSemverRangePrefix: ''

enableInlineBuilds: true

enableTransparentWorkspaces: false

nmHoistingLimits: dependencies

nodeLinker: node-modules

npmScopes:
  flex-development:
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN:-$PAT_BOT}
    npmRegistryServer: https://npm.pkg.github.com

patchFolder: ./patches

yarnPath: .yarn/releases/yarn-4.0.0-rc.39.cjs
