query ($limit: Int = 20, $owner: String!, $pr: Int!, $repo: String!) {
  repository(name: $repo, owner: $owner) {
    pullRequest(number: $pr) {
      closingIssuesReferences(
        first: $limit
        orderBy: { direction: ASC, field: CREATED_AT }
      ) {
        edges {
          node {
            number
          }
        }
      }
    }
  }
}
