/**
 * @file Internals - CompilerOptionsJson
 * @module mlly/internal/CompilerOptionsJson
 */

import type { CompilerOptionsValue, MapLike } from 'typescript'

/**
 * TypeScript compiler options provided by a user.
 *
 * @internal
 *
 * @see https://www.typescriptlang.org/tsconfig
 */
interface CompilerOptionsJson {
  allowJs?: boolean
  allowSyntheticDefaultImports?: boolean
  allowUmdGlobalAccess?: boolean
  allowUnreachableCode?: boolean
  allowUnusedLabels?: boolean
  alwaysStrict?: boolean
  assumeChangesOnlyAffectDirectDependencies?: boolean
  baseUrl?: string
  charset?: string
  checkJs?: boolean
  composite?: boolean
  declaration?: boolean
  declarationDir?: string
  declarationMap?: boolean
  disableReferencedProjectLoad?: boolean
  disableSizeLimit?: boolean
  disableSolutionSearching?: boolean
  disableSourceOfProjectReferenceRedirect?: boolean
  downlevelIteration?: boolean
  emitBOM?: boolean
  emitDeclarationOnly?: boolean
  emitDecoratorMetadata?: boolean
  esModuleInterop?: boolean
  exactOptionalPropertyTypes?: boolean
  experimentalDecorators?: boolean
  forceConsistentCasingInFileNames?: boolean
  importHelpers?: boolean
  importsNotUsedAsValues?: 'error' | 'preserve' | 'remove'
  incremental?: boolean
  inlineSourceMap?: boolean
  inlineSources?: boolean
  isolatedModules?: boolean
  jsx?: 'preserve' | 'react-jsx' | 'react-jsxdev' | 'react-native' | 'react'
  jsxFactory?: string
  jsxFragmentFactory?: string
  jsxImportSource?: string
  keyofStringsOnly?: boolean
  lib?: (
    | 'DOM.Iterable'
    | 'dom.iterable'
    | 'DOM'
    | 'dom'
    | 'ES5'
    | 'es5'
    | 'ES6'
    | 'es6'
    | 'ES7'
    | 'es7'
    | 'ES2015.Collection'
    | 'es2015.collection'
    | 'ES2015.Core'
    | 'es2015.core'
    | 'ES2015.Generator'
    | 'es2015.generator'
    | 'ES2015.Iterable'
    | 'es2015.iterable'
    | 'ES2015.Promise'
    | 'es2015.promise'
    | 'ES2015.Proxy'
    | 'es2015.proxy'
    | 'ES2015.Reflect'
    | 'es2015.reflect'
    | 'ES2015.Symbol.WellKnown'
    | 'es2015.symbol.wellknown'
    | 'ES2015.Symbol'
    | 'es2015.symbol'
    | 'ES2015'
    | 'es2015'
    | 'ES2016.Array.Include'
    | 'es2016.array.include'
    | 'ES2016'
    | 'es2016'
    | 'ES2017.Intl'
    | 'es2017.intl'
    | 'ES2017.Object'
    | 'es2017.object'
    | 'ES2017.SharedMemory'
    | 'es2017.sharedmemory'
    | 'ES2017.String'
    | 'es2017.string'
    | 'ES2017.TypedArrays'
    | 'es2017.typedarrays'
    | 'ES2017'
    | 'es2017'
    | 'ES2018.AsyncGenerator'
    | 'es2018.asyncgenerator'
    | 'ES2018.AsyncIterable'
    | 'es2018.asynciterable'
    | 'ES2018.Intl'
    | 'es2018.intl'
    | 'ES2018.Promise'
    | 'es2018.promise'
    | 'ES2018.Regexp'
    | 'es2018.regexp'
    | 'ES2018'
    | 'es2018'
    | 'ES2019.Array'
    | 'es2019.array'
    | 'ES2019.Object'
    | 'es2019.object'
    | 'ES2019.String'
    | 'es2019.string'
    | 'ES2019.Symbol'
    | 'es2019.symbol'
    | 'ES2019'
    | 'es2019'
    | 'ES2020.BigInt'
    | 'es2020.bigint'
    | 'ES2020.Intl'
    | 'es2020.intl'
    | 'ES2020.Promise'
    | 'es2020.promise'
    | 'ES2020.SharedMemory'
    | 'es2020.sharedmemory'
    | 'ES2020.String'
    | 'es2020.string'
    | 'ES2020.Symbol.WellKnown'
    | 'es2020.symbol.wellknown'
    | 'ES2020'
    | 'es2020'
    | 'ES2021.Promise'
    | 'es2021.promise'
    | 'ES2021.String'
    | 'es2021.string'
    | 'ES2021.WeakRef'
    | 'es2021.weakref'
    | 'ES2021'
    | 'es2021'
    | 'ESNext.Array'
    | 'esnext.array'
    | 'ESNext.AsyncIterable'
    | 'esnext.asynciterable'
    | 'ESNext.BigInt'
    | 'esnext.bigint'
    | 'ESNext.Intl'
    | 'esnext.intl'
    | 'ESNext.Promise'
    | 'esnext.promise'
    | 'ESNext.String'
    | 'esnext.string'
    | 'ESNext.Symbol'
    | 'esnext.symbol'
    | 'ESNext.WeakRef'
    | 'esnext.weakref'
    | 'ESNext'
    | 'esnext'
    | 'ScriptHost'
    | 'scripthost'
    | 'WebWorker.ImportScripts'
    | 'webworker.importscripts'
    | 'WebWorker.Iterable'
    | 'webworker.iterable'
    | 'WebWorker'
    | 'webworker'
  )[]
  locale?: string
  mapRoot?: string
  maxNodeModuleJsDepth?: number
  module?:
    | 'AMD'
    | 'amd'
    | 'CommonJS'
    | 'commonjs'
    | 'ES6'
    | 'es6'
    | 'ES2015'
    | 'es2015'
    | 'ES2020'
    | 'es2020'
    | 'ES2022'
    | 'es2022'
    | 'ESNext'
    | 'esnext'
    | 'Node16'
    | 'node16'
    | 'NodeNext'
    | 'nodenext'
    | 'None'
    | 'none'
    | 'System'
    | 'system'
    | 'UMD'
    | 'umd'
  moduleDetection?: 'auto' | 'force' | 'legacy'
  moduleResolution?: 'classic' | 'node' | 'node16' | 'nodenext'
  moduleSuffixes?: string[]
  newLine?: 'CRLF' | 'crlf' | 'LF' | 'lf'
  noEmit?: boolean
  noEmitHelpers?: boolean
  noEmitOnError?: boolean
  noErrorTruncation?: boolean
  noFallthroughCasesInSwitch?: boolean
  noImplicitAny?: boolean
  noImplicitOverride?: boolean
  noImplicitReturns?: boolean
  noImplicitThis?: boolean
  noImplicitUseStrict?: boolean
  noLib?: boolean
  noPropertyAccessFromIndexSignature?: boolean
  noResolve?: boolean
  noStrictGenericChecks?: boolean
  noUncheckedIndexedAccess?: boolean
  noUnusedLocals?: boolean
  noUnusedParameters?: boolean
  out?: string
  outDir?: string
  outFile?: string
  paths?: MapLike<string[]>
  preserveConstEnums?: boolean
  preserveSymlinks?: boolean
  preserveValueImports?: boolean
  project?: string
  reactNamespace?: string
  removeComments?: boolean
  resolveJsonModule?: boolean
  rootDir?: string
  rootDirs?: string[]
  skipDefaultLibCheck?: boolean
  skipLibCheck?: boolean
  sourceMap?: boolean
  sourceRoot?: string
  strict?: boolean
  strictBindCallApply?: boolean
  strictFunctionTypes?: boolean
  strictNullChecks?: boolean
  strictPropertyInitialization?: boolean
  stripInternal?: boolean
  suppressExcessPropertyErrors?: boolean
  suppressImplicitAnyIndexErrors?: boolean
  target?:
    | 'ES3'
    | 'es3'
    | 'ES5'
    | 'es5'
    | 'ES6'
    | 'es6'
    | 'ES2015'
    | 'es2015'
    | 'ES2016'
    | 'es2016'
    | 'ES2017'
    | 'es2017'
    | 'ES2018'
    | 'es2018'
    | 'ES2019'
    | 'es2019'
    | 'ES2020'
    | 'es2020'
    | 'ES2021'
    | 'es2021'
    | 'ESNext'
    | 'esnext'
  traceResolution?: boolean
  tsBuildInfoFile?: string
  typeRoots?: string[]
  types?: string[]
  useDefineForClassFields?: boolean
  useUnknownInCatchVariables?: boolean
  [option: string]: CompilerOptionsValue | undefined
}

export type { CompilerOptionsJson as default }
