#!/bin/sh

# Pre-Commit Workflow
#
# References:
#
# - https://github.com/okonet/lint-staged#command-line-flags
# - https://vitest.dev/guide/cli.html#changed

yarn typecheck --changed HEAD^
yarn check:types:build
lint-staged
