#!/bin/sh

set -e

# Pre-Commit Workflow
#
# References:
#
# - https://github.com/okonet/lint-staged#command-line-flags

cross-env LINT_STAGED=1 lint-staged --config=.lintstagedrc.json --relative --verbose
