# Label Syncer
#
# References:
#
# - https://github.com/micnncim/action-label-syncer

---
name: labels
on:
  create:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  workflow_dispatch:
permissions:
  issues: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  labels:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.ref }}
      - id: sync
        name: Sync labels
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/labels.yml
